import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/Components/header";
import Footer from "@/Components/footer";
import Sidebar from "@/Components/sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header></Header>
        <div className="flex w-9/12 h-[500px] border-2 border-red-500 mx-auto max-w-7xl mt-4">

          {/* left sidebar */}
          <div className="w-[500px] h-[400px] border-2 border-amber-700">
              <Sidebar></Sidebar>
          </div>

            {/* childerns */}
          <div>
              {children}
          </div>
        </div>
      
        <Footer></Footer>
      </body>
    </html>
  );
}
